backend:
  name: git-gateway
  branch: main

  commit_messages:
    create: Create {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}>
    update: Update {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}>
    delete: Delete {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}>
    uploadMedia: Upload "{{path}}" - {{author-name}} <{{author-login}}>
    deleteMedia: Delete "{{path}}" - {{author-name}} <{{author-login}}>
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}>

site_url: https://serenapastelapp.netlify.app

media_folder: "recursos/imagenes/uploads"
public_folder: "/recursos/imagenes/uploads"

locale: "es"

collections:
  - name: "catalogo"
    label: "Catálogo"
    files:

      - name: "15-anios"
        label: "15 Años"
        file: "data/15-anios.json"
        fields:
          - label: "Encabezado"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Etiqueta", name: "etiqueta", widget: "string" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "image" }

          - label: "Diseños"
            name: "disenos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Etiquetas", name: "tags", widget: "string", required: false }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Imagen", name: "imagen", widget: "image" }

      - name: "comestible"
        label: "Comestible"
        file: "data/comestible.json"
        fields:
          - label: "Encabezado"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Etiqueta", name: "etiqueta", widget: "string" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "image" }

          - label: "Diseños"
            name: "disenos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Etiquetas", name: "tags", widget: "string", required: false }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Imagen", name: "imagen", widget: "image" }

      - name: "cumpleanos"
        label: "Cumpleaños"
        file: "data/cumpleanos.json"
        fields:
          - label: "Encabezado"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Etiqueta", name: "etiqueta", widget: "string" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "image" }

          - label: "Diseños"
            name: "disenos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Etiquetas", name: "tags", widget: "string", required: false }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Imagen", name: "imagen", widget: "image" }

      - name: "grados"
        label: "Grados"
        file: "data/grados.json"
        fields:
          - label: "Encabezado"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Etiqueta", name: "etiqueta", widget: "string" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "image" }

          - label: "Diseños"
            name: "disenos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Etiquetas", name: "tags", widget: "string", required: false }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Imagen", name: "imagen", widget: "image" }

      - name: "sacramentos"
        label: "Sacramentos"
        file: "data/sacramentos.json"
        fields:
          - label: "Encabezado"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Etiqueta", name: "etiqueta", widget: "string" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "image" }

          - label: "Diseños"
            name: "disenos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Etiquetas", name: "tags", widget: "string", required: false }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Imagen", name: "imagen", widget: "image" }

      - name: "tematicas"
        label: "Temáticas"
        file: "data/tematicas.json"
        fields:
          - label: "Encabezado"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Etiqueta", name: "etiqueta", widget: "string" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "image" }

          - label: "Diseños"
            name: "disenos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Etiquetas", name: "tags", widget: "string", required: false }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Imagen", name: "imagen", widget: "image" }

      - name: "tortas-serena"
        label: "Tortas Serena"
        file: "data/tortas-serena.json"
        fields:
          - label: "Encabezado"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Etiqueta", name: "etiqueta", widget: "string" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "image" }

          - label: "Diseños"
            name: "disenos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Etiquetas", name: "tags", widget: "string", required: false }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Imagen", name: "imagen", widget: "image" }

      - name: "cupcakes"
        label: "Cupcakes"
        file: "data/cupcakes.json"
        fields:
          - label: "Encabezado"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Etiqueta", name: "etiqueta", widget: "string" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "image" }

          - label: "Diseños"
            name: "disenos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Etiquetas", name: "tags", widget: "string", required: false }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Imagen", name: "imagen", widget: "image" }

      - name: "alfajores"
        label: "Alfajores"
        file: "data/alfajores.json"
        fields:
          - label: "Encabezado"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Etiqueta", name: "etiqueta", widget: "string" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "image" }

          - label: "Diseños"
            name: "disenos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Etiquetas", name: "tags", widget: "string", required: false }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Imagen", name: "imagen", widget: "image" }

      - name: "galletas"
        label: "Galletas"
        file: "data/galletas.json"
        fields:
          - label: "Encabezado"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Etiqueta", name: "etiqueta", widget: "string" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "image" }

          - label: "Diseños"
            name: "disenos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Etiquetas", name: "tags", widget: "string", required: false }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Imagen", name: "imagen", widget: "image" }

      - name: "donas"
        label: "Donas"
        file: "data/donas.json"
        fields:
          - label: "Encabezado"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Etiqueta", name: "etiqueta", widget: "string" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "image" }

          - label: "Diseños"
            name: "disenos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Etiquetas", name: "tags", widget: "string", required: false }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Imagen", name: "imagen", widget: "image" }

      - name: "desayunos"
        label: "Desayunos"
        file: "data/desayunos.json"
        fields:
          - label: "Encabezado"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Etiqueta", name: "etiqueta", widget: "string" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "image" }

          - label: "Diseños"
            name: "disenos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Etiquetas", name: "tags", widget: "string", required: false }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Imagen", name: "imagen", widget: "image" }